#!/bin/bash
# doing some preparations and general configurations

# software and updates
yum install epel-release -y && \
yum install -y \
bash-completion \
bind-utils \
bridge-utils \
ca-certificates \
curl wget \
file \
git \
iproute iputils \
less lsof \
mlocate \
net-tools \nmap \
nmap-ncat \
openssl-devel \
rsync \
sysvinit-tools \
tcpdump \
telnet \
vim \
yum-utils \
zip unzip \
gcc gcc-c++
 
yum update -y && \
reboot

# security configs
ssh-keygen -q -b 2048 -N '' -t ed25519 -f ~/.ssh/id_ed25519 && \
echo "#" >> ~/.ssh/authorized_keys
 
# disable selinux
sed -i~ -r '/^SELINUX/,+0 s/enforcing/disabled/;s/permissive/disabled/' /etc/selinux/config
setenforce 0
 
# configure iptables
yum remove firewalld -y
yum install iptables-services -y
 
cat <<EOF> /root/iptables.saved.baseline
# Generated by iptables-save v1.4.21 on Thu Jan 28 22:39:13 2021
*filter
:INPUT ACCEPT [168775:26909562]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [172475:33184614]
-A INPUT -s 10.100.88.99/32 -p tcp -m multiport --dports 80,111,443,514,1024:65535 -m comment --comment "some unwanted server" -j REJECT --reject-with icmp-host-prohibited
COMMIT
# Completed on Thu Jan 28 22:39:13 2021
# Generated by iptables-save v1.4.21 on Thu Jan 28 22:39:13 2021
*nat
:PREROUTING ACCEPT [5075:378277]
:INPUT ACCEPT [3876:306337]
:OUTPUT ACCEPT [1205:96788]
:POSTROUTING ACCEPT [1205:96788]
COMMIT
# Completed on Thu Jan 28 22:39:13 2021
EOF
 
systemctl enable --now iptables.service
 
iptables-restore < /root/iptables.saved.baseline

service iptables save
